Repository johnvees/FinalProject-SecondHand, pull requests merged in 2022-06, with the labels that each got.

#2 config splash screen and add image for splash screen
  App.js
  android/app/build.gradle
  android/app/src/main/java/com/secondhand/MainActivity.java
  android/app/src/main/java/com/secondhand/MainApplication.java
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-hdpi/launch_screen.png
  android/app/src/main/res/mipmap-mdpi/launch_screen.png
  android/app/src/main/res/mipmap-xhdpi/launch_screen.png
  android/app/src/main/res/mipmap-xxhdpi/launch_screen.png
  android/app/src/main/res/mipmap-xxxhdpi/launch_screen.png
  android/app/src/main/res/values/colors.xml
  android/settings.gradle
  ios/Podfile
Labels: enhancement

#3 config splash screen and add image for splash screen
  App.js
  android/app/build.gradle
  android/app/src/main/java/com/secondhand/MainActivity.java
  android/app/src/main/java/com/secondhand/MainApplication.java
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-hdpi/launch_screen.png
  android/app/src/main/res/mipmap-mdpi/launch_screen.png
  android/app/src/main/res/mipmap-xhdpi/launch_screen.png
  android/app/src/main/res/mipmap-xxhdpi/launch_screen.png
  android/app/src/main/res/mipmap-xxxhdpi/launch_screen.png
  android/app/src/main/res/values/colors.xml
  android/settings.gradle
  ios/Podfile
Labels: configs

#6 Feature/login
  App.js
  src/screens/Login/index.js
  src/screens/index.js
  src/utils/helpers/index.js
  src/utils/hooks/index.js
  src/utils/index.js
Labels: enhancement

#4 configure for vector icons library
  android/app/build.gradle
  android/app/src/main/assets/fonts/AntDesign.ttf
  android/app/src/main/assets/fonts/Entypo.ttf
  android/app/src/main/assets/fonts/EvilIcons.ttf
  android/app/src/main/assets/fonts/Feather.ttf
  android/app/src/main/assets/fonts/FontAwesome.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Brands.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Regular.ttf
  android/app/src/main/assets/fonts/FontAwesome5_Solid.ttf
  android/app/src/main/assets/fonts/Fontisto.ttf
  android/app/src/main/assets/fonts/Foundation.ttf
  android/app/src/main/assets/fonts/Ionicons.ttf
  android/app/src/main/assets/fonts/MaterialCommunityIcons.ttf
  android/app/src/main/assets/fonts/MaterialIcons.ttf
  android/app/src/main/assets/fonts/Octicons.ttf
  android/app/src/main/assets/fonts/SimpleLineIcons.ttf
  android/app/src/main/assets/fonts/Zocial.ttf
  android/app/src/main/java/com/secondhand/MainApplication.java
  android/settings.gradle
  ios/Podfile
  ios/SecondHand.xcodeproj/project.pbxproj
  ios/SecondHand/Info.plist
  react-native.config.js
Labels: configs

#7 Feature/register
  src/screens/Register/index.js
  src/screens/index.js
  src/utils/hooks/index.js
Labels: enhancement

#10 Configs/stack navigator
  App.js
Labels: configs

#14 rubah icon app
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/ic_launcher-web.png
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/playstore-icon.png
  android/app/src/main/res/values/ic_launcher_background.xml
Labels: configs

#21 Configs/stack navigator
  App.js
Labels: configs

#18 Configs Ilustration
  src/assets/images/gift.png
  src/assets/images/no_image.png
  src/assets/images/no_product.png
Labels: configs

#12 Add Colors : MyColors
  App.js
  src/Assets/Colors/index.js
Labels: configs

#13 Add Global Fonts OpenSans/Poppins
  App.js
  android/app/src/main/assets/fonts/Poppins-Bold.ttf
  android/app/src/main/assets/fonts/Poppins-Medium.ttf
  android/app/src/main/assets/fonts/Poppins-Regular.ttf
  src/utils/fonts/index.js
Labels: configs

#17 Configs/biometric auth
  App.js
  src/component/bio-auth/index.js
Labels: configs

#16 install package redux and setup redux
  App.js
  package.json
  src/redux/reducer.js
  src/redux/store.js
  yarn.lock
Labels: configs

#23 Components/button
  App.js
  package.json
  src/components/Button/example.js
  src/components/Button/index.js
  src/components/index.js
  src/routes/BottomTab.js
  src/screens/Akun/index.js
  src/screens/DaftarJual/index.js
  src/screens/Home/index.js
  src/screens/Jual/index.js
  src/screens/Notifikasi/index.js
  src/screens/index.js
Labels: components

#26 configure number format and give example
  App.js
  src/components/NumberFormat/example.js
  src/components/NumberFormat/index.js
  src/components/index.js
Labels: components

#25 config for sonar cloud
  .github/workflows/build.yml
  .github/worklflows/CD-proccess.yml
  .github/worklflows/CI-proccess.yml
  sonar-project.properties
Labels: configs

#28 Components/card notification
  src/components/CardNotification/index.js
Labels: components

#19 Configs/ci cd
  .eslintrc.js
  .github/workflows/CD-proccess.yml
  .github/workflows/CI-proccess.yml
  package.json
  yarn.lock
Labels: configs

#37 Components/open bottom sheet
  App.js
  src/components/bottom-sheet/index.js
Labels: components

#27 Done : Text Input
  App.js
  src/components/Gap/index.js
  src/components/TextInput/index.js
Labels: components

#15 config firebase
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  src/utils/Firebase/index.js
Labels: configs

#39 Fix Force Close : Firebase
  android/app/build.gradle
  android/build.gradle
  package.json
  yarn.lock
Labels: configs
